### ISSUE TITLE
Replace Date and Calendar with java.time classes

### ISSUE THREAD

**Issue by michaelboyles** [caseyscarborough/wanikani-api#5]
j.u.Date has a fair few well-documented problems that java.time classes fixed. Time to replace them? It would be backwards-incompatible.

https://stackoverflow.com/questions/1969442/whats-wrong-with-java-date-time-api

**Comment by caseyscarborough** [comment]
@michaelboyles I migrated everything over to LocalDateTime, but then I realized this probably isn't the best option, considering LocalDateTime doesn't actually represent a point in time.

Some additional info at these links:

- https://stackoverflow.com/questions/32437550/whats-the-difference-between-instant-and-localdatetime/32443004#32443004
- http://blog.schauderhaft.de/2018/03/14/dont-use-localdatetime/

I'm leaning more toward using ZonedDateTime or Instant now. Let me know if you have any suggestions.

The updated code is in the migrate-to-java-util-time branch for now.

**Comment by michaelboyles** [comment]
@caseyscarborough Looking at their API, ZonedDateTime is probably the most correct choice.

e.g.
"data_updated_at": "2017-03-30T11:31:20.438432**Z**",

Z is a shorthand for UTC, so the timestamps they're using are always including a zone, it's just always the same one that uses no offset.

In a hypothetical future that won't happen, maybe WK would change Z to '+05:00'. If some user of this library actually cared what the offset was (they won't), then ZonedDateTime would retain that for them, while Instant would throw it away.

**Comment by michaelboyles** [comment]
Well actually, all of what I said applies for timestamps coming _in_, but there's a couple of place where timestamps go _out_ in query parameters, like `updated_after`.

It's needlessly restrictive to make a user of this lib provide a timestamp with an offset when the offset can't possibly affect the result. So for outgoing things Instant makes more sense. As it happens, WK only seems to support query params in UTC using the 'Z' notation anyway - it throws error with any other offset.

**Comment by caseyscarborough** [comment]
@michaelboyles thanks for the feedback, I agree completely. I took the best of both worlds and stored the values coming back from the API as ZonedDateTime, but allow the user to specify either Instant, ZonedDateTime, or OffsetDateTime in the requests. I opened #7 for it if you wouldn't mind taking a look.
