### ISSUE TITLE
Add toStrings, maybe equals and hashCode, etc.

### ISSUE THREAD

**Issue by michaelboyles** [caseyscarborough/wanikani-api#8]
It would be convenient if model classes had `toString` methods. Maybe `equals` and `hashCode` too.

[Lombok](https://projectlombok.org/) would make that really easy, and would let us remove some of the getter/setter boilerplate too. How do you feel about it?

**Comment by caseyscarborough** [comment]
Lombok would be great, definitely on board with that (not sure why I didn't use it to begin with).

**Comment by caseyscarborough** [comment]
Closed in PR #15.
